// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWbUNl_XhMxXcCoqBvtGr46cPrjI9g15w',
    appId: '1:809453709751:web:9ecb69980058492fc9e032',
    messagingSenderId: '809453709751',
    projectId: 'uberproject-82287',
    authDomain: 'uberproject-82287.firebaseapp.com',
    storageBucket: 'uberproject-82287.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyB6FFkTIRW-v0VU5AWeifoEUVDMqw8c',
    appId: '1:809453709751:android:a7c131c18dce04d2c9e032',
    messagingSenderId: '809453709751',
    projectId: 'uberproject-82287',
    storageBucket: 'uberproject-82287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz09aKlZ8cQpp5xuO3j6kRPb_-S9J-fuI',
    appId: '1:809453709751:ios:928846c887e7ad7ec9e032',
    messagingSenderId: '809453709751',
    projectId: 'uberproject-82287',
    storageBucket: 'uberproject-82287.appspot.com',
    iosBundleId: 'com.example.uberProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz09aKlZ8cQpp5xuO3j6kRPb_-S9J-fuI',
    appId: '1:809453709751:ios:89103a8b23515c8cc9e032',
    messagingSenderId: '809453709751',
    projectId: 'uberproject-82287',
    storageBucket: 'uberproject-82287.appspot.com',
    iosBundleId: 'com.example.uberProject.RunnerTests',
  );
}
